# ======================================================================================================================
# == LICENSE:       Copyright (c) 2023 Kevin De Coninck
# ==
# ==                Permission is hereby granted, free of charge, to any person
# ==                obtaining a copy of this software and associated documentation
# ==                files (the "Software"), to deal in the Software without
# ==                restriction, including without limitation the rights to use,
# ==                copy, modify, merge, publish, distribute, sublicense, and/or sell
# ==                copies of the Software, and to permit persons to whom the
# ==                Software is furnished to do so, subject to the following
# ==                conditions:
# ==
# ==                The above copyright notice and this permission notice shall be
# ==                included in all copies or substantial portions of the Software.
# ==
# ==                THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# ==                EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# ==                OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# ==                NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# ==                HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# ==                WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# ==                FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# ==                OTHER DEALINGS IN THE SOFTWARE.
# ======================================================================================================================

# Information about the Github workflow.
name: Test .NET Solution
run-name: Test .NET Solution on "${{ github.ref_name }}" by "@${{ github.actor }}"

# This workflow is executed when:
# - It's manually triggered.
#
# - The Github workflow "Build .NET Solution" completed.
on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "Build .NET Solution" ]
    types: 
      - completed

# The jobs which are part of this Github workflow.
jobs:
  test:
    name: Build on "${{ matrix.os }}" using ".NET ${{ matrix.dotnet-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        dotnet-version: [ '7.0.102' ]

    steps:
    - name: GIT Clone
      uses: actions/checkout@v3

    - name: Setup ".NET ${{ matrix.dotnet-version }}"
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Restore NuGet packages (dotnet restore)
      working-directory: app
      run: dotnet restore

    - name: Build .NET Solution (dotnet build)
      working-directory: app
      run: dotnet build --no-incremental --no-restore /p:CIBuild=true

    - name: Run tests (dotnet test)
      working-directory: app
      env:
        AUTH0_TOKEN_ENDPOINT: ${{ secrets.AUTH0_TOKEN_ENDPOINT }}
        AUTH0_USERNAME: ${{ secrets.AUTH0_USERNAME }}
        AUTH0_PASSWORD: ${{ secrets.AUTH0_PASSWORD }}
        AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        AUTH0_VALID_AUDIENCE: ${{ secrets.AUTH0_VALID_AUDIENCE }}
        AUTH0_VALID_ISSUER: ${{ secrets.AUTH0_VALID_ISSUER }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
      run: dotnet test --no-build --no-restore --logger trx --results-directory "TestResults-${{ matrix.dotnet-version }}"

    - name: Upload results.
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results-${{ matrix.dotnet-version }}
        path: app/TestResults-${{ matrix.dotnet-version }}
